language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
install:
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt
script: pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: NOnHVsP/lA8C4rUuwN6MgpsE8+0ac9JvOL/oRkvSMfilT2t6O/43DYOn/GywwTAH9KwY0XlXivmSF4A7aievNCrFjuzJ+w615+FUlxVS6dJwL5rdlMFemSmO4DVGI+efVFMjZLBQzkMlDMLGHkGk673lJX0PRTKY1rpJfG7wsB9eAHwJK83aNplWH0IFeudjDvvfOcJk6gfQXgfKpYADdBZ0DZsEb3fp2BJXBVWSkw4I8K1AtUdcyJVFiepKf0RmWxS4UW/sYzQO2Bm23UWztaW3sUyhwzKM50FF0s5QM/7VuqZB1hwrzI5pQy0XE8C8UnHgdrfOh8g4FslAEaiaNWT7edJWHw5ehrTKBVh+8tW6yuIAPoMfcShv1MfiRrAf5qn/0sY2EVtZeIAnSoBpEaf79GZCJJkRBxYMxV2FkTwcX8Di65/cdAVKE2MV/Yq8K+OujSyrrdu+YdxeSg9zZGjhaN9Q6zLKQHjMcj/LX2Rrsbmv1ZrGN0VX7l+gVVkuDl6e/LWEd5s2VJNbfEqwrNUrLAYikkavGTlYy7EFq4y9WnHA63M0KYgwKu3UcV8F+oqjv1bYIMyiiKTsMIR9amcNXeoYmMrzm7+zShdNeYuEgkcmVu37fLNyzFixI9AMqPNLeCfAjXKAg1ew6AAfKJ/pHrmbFWJ+hzqX/t6hCE8=
  on:
    python: 3.8
    branch: master
